### ISSUE TITLE
Create a file science-fiction.md.

### ISSUE THREAD

**Issue by shashwat28nov** [shashwat28nov/Books#8]
Create a file for Science Fiction as science-fiction.md. Make sure you follow the proper formatting.

**Comment by Carolis** [comment]
@shashwat28nov Can I take this one?

**Comment by shashwat28nov** [comment]
@Carolis Yes, definitely. You can.

**Comment by gaurang7goel** [comment]
HI, if the issue is still open can I do it.

**Comment by shashwat28nov** [comment]
@gaurang7goel  Yes, you can.

**Comment by gaurang7goel** [comment]
Pls look over my PR.

**Comment by gaurang7goel** [comment]
Thanks

**Comment by shashwat28nov** [comment]
@gaurang7goel Yes, great work. I have merged it.
