### ISSUE TITLE
Create a file young-adult.md

### ISSUE THREAD

**Issue by shashwat28nov** [shashwat28nov/Books#9]
Create a file young-adult.md for books that belong to the genre Young Adult. Make sure to follow the proper formatting.

**Comment by bchetanrao** [comment]
I would like to take up this issue.

**Comment by bchetanrao** [comment]
I am sorry @shashwat28nov , I didn't know that first you will assign this issue to someone then they are supposed to send a PR. I am new to github so i made a PR before you even assigned this issue to me. My sincere apologies. Please look at my PR and merge it if it suits well to the issue.

**Comment by shashwat28nov** [comment]
@bchetanrao  You can self assign the issue if you see no open/closed PR made. No need for apologies.
